"""
Abstract repository interfaces — Time Compression Engine.

All concrete repository implementations (InMemory, PostgreSQL) implement
these protocols. Routes and services depend only on these interfaces,
making the backend storage-agnostic.

Current implementations:
- InMemory (app/repositories/inmemory/) — v1.0.1, no DB required
- PostgreSQL (app/repositories/*.py)    — v1.1, requires DB migration
"""

from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class VideoRepo(Protocol):
    async def create(self, record: dict) -> dict: ...
    async def get(self, video_id: str) -> dict | None: ...
    async def list(self) -> list[dict]: ...
    async def delete(self, video_id: str) -> bool: ...


@runtime_checkable
class JobRepo(Protocol):
    async def create(self, record: dict) -> dict: ...
    async def get(self, job_id: str) -> dict | None: ...
    async def list(self) -> list[dict]: ...
    async def update(self, job_id: str, fields: dict) -> dict | None: ...
    async def get_by_video(self, video_id: str) -> list[dict]: ...


@runtime_checkable
class EventRepo(Protocol):
    async def create_many(self, records: list[dict]) -> list[dict]: ...
    async def list_by_video(self, video_id: str) -> list[dict]: ...
    async def list_all(self) -> list[dict]: ...
    async def get(self, event_id: str) -> dict | None: ...
