"""
Video Frame Quality Analyzer — TCE Accuracy Overhaul v1.0.1.

Classifies each video frame into one of four quality classes:
  NORMAL           — adequate illumination, proceed with standard detection
  LOW_LIGHT        — dim but usable; apply CLAHE preprocessing
  VERY_LOW_LIGHT   — very dark; apply CLAHE + gamma correction
  UNUSABLE         — too dark or too blurry for reliable detection; skip or flag

Computed per-frame metrics:
  mean_luminance    — mean pixel brightness (0–255)
  luminance_std     — std dev of pixel luminance (contrast proxy)
  blur_score        — Laplacian variance (high = sharp, low = blurry)
  dark_pixel_ratio  — fraction of pixels with luminance < 30
  histogram_spread  — p95 − p5 of luminance histogram (dynamic range)

Design principles:
  - Thresholds are configurable (not magic numbers buried in conditionals).
  - Enhanced frames record their preprocessing_mode so detection results are
    attributable to the right preprocessing step.
  - UNUSABLE frames are flagged for skip_detection rather than forcing YOLO
    to run on garbage input (which generates high-confidence false positives).
  - Does NOT chain all enhancements blindly — each step is conditional.

Why this matters (Scenarios B, C from the overhaul spec):
  YOLO's default confidence calibration assumes well-lit, high-contrast frames.
  On dark frames, YOLO may miss people entirely OR produce spurious detections
  from noise patterns. Classifying frames first lets us apply targeted
  preprocessing only where needed, and report honest confidence degradation.

Branch: experiment/v1.0.1-accuracy-overhaul
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Quality Classification
# ---------------------------------------------------------------------------

class QualityClass(str, Enum):
    """Frame quality classification."""
    NORMAL          = "normal"
    LOW_LIGHT       = "low_light"
    VERY_LOW_LIGHT  = "very_low_light"
    UNUSABLE        = "unusable"


@dataclass
class QualityThresholds:
    """
    Configurable thresholds for quality classification.

    All values are defaults tuned empirically for indoor CCTV footage.
    Override by passing a custom instance to analyze_frame() / analyze_video_quality().
    """
    # UNUSABLE: either too blurry OR too dark to trust any detection
    unusable_blur_score: float      = 15.0   # Laplacian variance below this = blurry
    unusable_luminance: float       = 5.0    # Mean luminance below this = nearly black

    # VERY_LOW_LIGHT: very dark — applies CLAHE + gamma
    very_low_light_luminance: float = 30.0   # Mean luminance
    very_low_light_dark_ratio: float = 0.60  # Fraction of pixels below 30 luma

    # LOW_LIGHT: dim but usable — applies CLAHE only
    low_light_luminance: float      = 60.0
    low_light_dark_ratio: float     = 0.30


DEFAULT_THRESHOLDS = QualityThresholds()


@dataclass
class FrameQuality:
    """
    Quality analysis result for a single video frame.

    Fields:
        frame_number:     Frame index in the original video.
        timestamp_ms:     Timestamp in milliseconds.
        mean_luminance:   Mean pixel luminance [0, 255].
        luminance_std:    Standard deviation of luminance (contrast proxy).
        blur_score:       Laplacian variance. Higher = sharper.
        dark_pixel_ratio: Fraction of pixels with luminance < 30.
        histogram_spread: p95 − p5 of luminance values (dynamic range).
        quality_class:    Classification (NORMAL/LOW_LIGHT/VERY_LOW_LIGHT/UNUSABLE).
        recommended_preprocessing: Preprocessing mode string for low_light.py.
    """
    frame_number: int
    timestamp_ms: float
    mean_luminance: float
    luminance_std: float
    blur_score: float
    dark_pixel_ratio: float
    histogram_spread: float
    quality_class: QualityClass
    recommended_preprocessing: str   # 'off' | 'clahe' | 'clahe_gamma'

    @property
    def skip_detection_recommended(self) -> bool:
        """True if this frame is too poor quality to run reliable detection on."""
        return self.quality_class == QualityClass.UNUSABLE



@dataclass
class VideoQualityReport:
    """
    Aggregate quality report for an entire video (or video segment).

    Generated by analyze_video_quality() after processing all frames.
    Stored in context.metadata["video_quality_report"] by S04.
    """
    total_frames: int
    dominant_quality_class: QualityClass
    mean_luminance: float
    mean_blur_score: float
    low_light_ratio: float        # Fraction of frames classified LOW_LIGHT
    very_low_light_ratio: float   # Fraction of frames classified VERY_LOW_LIGHT
    unusable_ratio: float         # Fraction of frames classified UNUSABLE
    recommended_preprocessing: str  # Suggested global preprocessing mode
    per_frame: list[FrameQuality] = field(default_factory=list)

    def summary_dict(self) -> dict:
        """Return a JSON-serializable summary (without per_frame data)."""
        return {
            "total_frames": self.total_frames,
            "dominant_quality_class": self.dominant_quality_class.value,
            "mean_luminance": round(self.mean_luminance, 2),
            "mean_blur_score": round(self.mean_blur_score, 2),
            "low_light_ratio": round(self.low_light_ratio, 3),
            "very_low_light_ratio": round(self.very_low_light_ratio, 3),
            "unusable_ratio": round(self.unusable_ratio, 3),
            "recommended_preprocessing": self.recommended_preprocessing,
        }


# ---------------------------------------------------------------------------
# Per-frame analysis
# ---------------------------------------------------------------------------

def analyze_frame(
    frame_bgr: np.ndarray,
    frame_number: int = 0,
    timestamp_ms: float = 0.0,
    thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
) -> FrameQuality:
    """
    Analyze a single BGR frame (numpy array) and return its FrameQuality.

    Args:
        frame_bgr:     OpenCV BGR frame as uint8 numpy array (H, W, 3).
        frame_number:  Frame index for logging.
        timestamp_ms:  Timestamp for this frame.
        thresholds:    Classification thresholds (use DEFAULT_THRESHOLDS or override).

    Returns:
        FrameQuality with all metrics computed and quality_class assigned.
    """
    if frame_bgr is None or frame_bgr.size == 0:
        return FrameQuality(
            frame_number=frame_number,
            timestamp_ms=timestamp_ms,
            mean_luminance=0.0,
            luminance_std=0.0,
            blur_score=0.0,
            dark_pixel_ratio=1.0,
            histogram_spread=0.0,
            quality_class=QualityClass.UNUSABLE,
            recommended_preprocessing="off",
        )

    # Convert to grayscale (ITU-R 601 weights via OpenCV default)
    try:
        import cv2
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    except Exception:
        # Fallback: manual luma conversion
        b = frame_bgr[:, :, 0].astype(np.float32)
        g = frame_bgr[:, :, 1].astype(np.float32)
        r = frame_bgr[:, :, 2].astype(np.float32)
        gray = 0.114 * b + 0.587 * g + 0.299 * r

    # 1. Mean luminance and std (contrast proxy)
    mean_lum = float(gray.mean())
    lum_std  = float(gray.std())

    # 2. Blur score — Laplacian variance
    #    High = lots of edges = sharp; Low = smooth = blurry or featureless
    try:
        import cv2
        lap = cv2.Laplacian(gray.astype(np.uint8), cv2.CV_64F)
        blur_score = float(lap.var())
    except Exception:
        # Manual 3×3 Laplacian kernel
        kernel = np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=np.float32)
        from scipy.signal import convolve2d
        lap = convolve2d(gray, kernel, mode="same")
        blur_score = float(np.var(lap))

    # 3. Dark pixel ratio — fraction with luminance < 30
    dark_pixel_ratio = float((gray < 30).sum()) / float(gray.size)

    # 4. Histogram spread — p95 minus p5 (dynamic range indicator)
    p5  = float(np.percentile(gray, 5))
    p95 = float(np.percentile(gray, 95))
    histogram_spread = p95 - p5

    # 5. Classify
    quality_class, preprocessing = _classify(
        mean_lum, blur_score, dark_pixel_ratio, thresholds
    )

    return FrameQuality(
        frame_number=frame_number,
        timestamp_ms=timestamp_ms,
        mean_luminance=round(mean_lum, 2),
        luminance_std=round(lum_std, 2),
        blur_score=round(blur_score, 2),
        dark_pixel_ratio=round(dark_pixel_ratio, 4),
        histogram_spread=round(histogram_spread, 2),
        quality_class=quality_class,
        recommended_preprocessing=preprocessing,
    )


def analyze_frame_from_path(
    frame_path: str,
    frame_number: int = 0,
    timestamp_ms: float = 0.0,
    thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
) -> Optional[FrameQuality]:
    """
    Analyze a single frame from a file path. Returns None if file cannot be read.

    Used by S04 when frames are stored as JPEG files rather than in-memory arrays.
    """
    try:
        import cv2
        frame = cv2.imread(frame_path)
        if frame is None:
            logger.debug("Could not read frame: %s", frame_path)
            return None
        return analyze_frame(frame, frame_number, timestamp_ms, thresholds)
    except Exception as exc:
        logger.warning("Quality analysis failed for %s: %s", frame_path, exc)
        return None


def _classify(
    mean_lum: float,
    blur_score: float,
    dark_pixel_ratio: float,
    t: QualityThresholds,
) -> tuple[QualityClass, str]:
    """
    Return (QualityClass, preprocessing_mode) given computed metrics.

    Priority: UNUSABLE checked first (worst case), then VERY_LOW_LIGHT, then LOW_LIGHT.
    """
    # UNUSABLE: below minimum usable quality
    if blur_score < t.unusable_blur_score or mean_lum < t.unusable_luminance:
        return QualityClass.UNUSABLE, "off"

    # VERY_LOW_LIGHT: very dark scene
    if mean_lum < t.very_low_light_luminance and dark_pixel_ratio >= t.very_low_light_dark_ratio:
        return QualityClass.VERY_LOW_LIGHT, "clahe_gamma"

    # LOW_LIGHT: dim but usable
    if mean_lum < t.low_light_luminance and dark_pixel_ratio >= t.low_light_dark_ratio:
        return QualityClass.LOW_LIGHT, "clahe"

    return QualityClass.NORMAL, "off"



# ---------------------------------------------------------------------------
# Video-level analysis
# ---------------------------------------------------------------------------

def analyze_video_quality(
    frame_paths: list[str],
    frame_numbers: list[int],
    timestamps_ms: list[float],
    thresholds: QualityThresholds = DEFAULT_THRESHOLDS,
    sample_rate: int = 1,
) -> VideoQualityReport:
    """
    Analyze frame quality for a sequence of frames and return a VideoQualityReport.

    Args:
        frame_paths:   Absolute paths to extracted frame files.
        frame_numbers: Corresponding frame numbers.
        timestamps_ms: Corresponding timestamps in milliseconds.
        thresholds:    Quality classification thresholds.
        sample_rate:   Analyze every Nth frame (1 = all frames, 5 = every 5th).
                       For long videos, use sample_rate=5 to reduce overhead.

    Returns:
        VideoQualityReport with per-frame data and aggregate statistics.
    """
    if not frame_paths:
        return VideoQualityReport(
            total_frames=0,
            dominant_quality_class=QualityClass.NORMAL,
            mean_luminance=128.0,
            mean_blur_score=100.0,
            low_light_ratio=0.0,
            very_low_light_ratio=0.0,
            unusable_ratio=0.0,
            recommended_preprocessing="off",
            per_frame=[],
        )

    per_frame: list[FrameQuality] = []
    sampled_paths = list(zip(frame_paths, frame_numbers, timestamps_ms))
    if sample_rate > 1:
        sampled_paths = sampled_paths[::sample_rate]

    for path, fn, ts in sampled_paths:
        fq = analyze_frame_from_path(path, fn, ts, thresholds)
        if fq is not None:
            per_frame.append(fq)

    if not per_frame:
        return VideoQualityReport(
            total_frames=len(frame_paths),
            dominant_quality_class=QualityClass.NORMAL,
            mean_luminance=128.0,
            mean_blur_score=100.0,
            low_light_ratio=0.0,
            very_low_light_ratio=0.0,
            unusable_ratio=0.0,
            recommended_preprocessing="off",
            per_frame=[],
        )

    # Aggregate
    n = len(per_frame)
    mean_lum   = sum(f.mean_luminance for f in per_frame) / n
    mean_blur  = sum(f.blur_score for f in per_frame) / n

    counts = {cls: 0 for cls in QualityClass}
    for f in per_frame:
        counts[f.quality_class] += 1

    low_light_ratio      = (counts[QualityClass.LOW_LIGHT] + counts[QualityClass.VERY_LOW_LIGHT]) / n
    very_low_light_ratio = counts[QualityClass.VERY_LOW_LIGHT] / n
    unusable_ratio       = counts[QualityClass.UNUSABLE] / n

    # Dominant class (most frequent)
    dominant = max(counts, key=counts.get)  # type: ignore[arg-type]

    # Recommended global preprocessing
    if very_low_light_ratio > 0.3:
        recommended = "clahe_gamma"
    elif low_light_ratio > 0.3:
        recommended = "clahe"
    else:
        recommended = "off"

    logger.info(
        "[QualityAnalyzer] %d frames: normal=%.0f%% low_light=%.0f%% "
        "very_low=%.0f%% unusable=%.0f%% mean_lum=%.1f mean_blur=%.1f",
        n,
        counts[QualityClass.NORMAL] / n * 100,
        counts[QualityClass.LOW_LIGHT] / n * 100,
        counts[QualityClass.VERY_LOW_LIGHT] / n * 100,
        counts[QualityClass.UNUSABLE] / n * 100,
        mean_lum,
        mean_blur,
    )

    return VideoQualityReport(
        total_frames=len(frame_paths),
        dominant_quality_class=dominant,
        mean_luminance=round(mean_lum, 2),
        mean_blur_score=round(mean_blur, 2),
        low_light_ratio=round(low_light_ratio, 3),
        very_low_light_ratio=round(very_low_light_ratio, 3),
        unusable_ratio=round(unusable_ratio, 3),
        recommended_preprocessing=recommended,
        per_frame=per_frame,
    )
